Repository codeit-bootcamp-frontend/3-Weekly-Mission, pull requests merged in 2024-02, with the labels that each got.

#220 [오영곤] Week8
  jsconfig.json
  public/images/check.svg
  public/images/facebook.svg
  public/images/kakao.svg
  public/images/link.svg
  public/images/modal-close.png
  public/index.html
  src/App.js
  src/api/api.js
  src/components/contents/cardList/KebebPopover.js
  src/components/contents/cardList/cardList.css
  src/components/contents/cardList/cardList.js
  src/components/contents/contents.js
  src/components/contents/folderContents/FolderContents.js
  src/components/contents/folderContents/FolderGroup.js
  src/components/contents/searchBar/SearchBar.js
  src/components/contents/sharedContents/SharedContents.js
  src/components/footer/footer.js
  src/components/header/FolderHeader.js
  src/components/header/SharedHeader.js
  src/components/header/folderHeader/FolderHeader.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/sharedHeader/SharedHeader.js
  src/components/modal/BaseModal.js
  src/components/modal/index.js
  src/components/modal/modal.css
  src/components/modal/modal.js
  src/components/modal/modalType/AddFolderModal.js
  src/components/modal/modalType/AddModal.js
  src/components/modal/modalType/DeleteModal.js
  src/components/modal/modalType/EditModal.js
  src/components/modal/modalType/ShareModal.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/styles/common.css
  src/utils/share/shareKakao.js
Labels: 매운맛🔥

#255 [조예진] week12
  .gitignore
  package-lock.json
  package.json
  public/assets/_close.svg
  public/index.html
  src/App.tsx
  src/apis/api.ts
  src/components/AddLinkForm/AddLinkForm.module.css
  src/components/AddLinkForm/AddLinkForm.tsx
  src/components/CardList/Card/Card.module.css
  src/components/CardList/Card/Card.tsx
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.module.css
  src/components/CardList/CardList.tsx
  src/components/CardList/OptionBox.tsx
  src/components/Content/Content.jsx
  src/components/Content/Content.module.css
  src/components/Content/Content.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/Folder/FolderButton.tsx
  src/components/Folder/FolderList.tsx
  src/components/Folder/constants.ts
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/SelectFolderBox.tsx
  src/components/Modal/SelectFolderItem.tsx
  src/components/Modal/ShareIconBox.jsx
  src/components/Modal/ShareIconBox.tsx
  src/components/Navbar/Navbar.tsx
  src/components/PopOver/PopOver.tsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/components/SearchBar/SearchBar.tsx
  src/global.d.ts
  src/hooks/useFolderData.ts
  src/hooks/useLinkDataByFolderId.ts
  src/hooks/useUserData.ts
  src/index.js
  src/index.tsx
  src/pages/FolderPage.tsx
  src/pages/SharedLinkPage.tsx
  src/utils/calDate.ts
  src/utils/calElapsedTime.ts
  tsconfig.json
Labels: 순한맛🐑 

#256 [김성훈] Week12
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/images/close.svg
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/components/ActionContainer.tsx
  src/components/Cardlist.tsx
  src/components/FloatingActionButton.tsx
  src/components/FolderContent.tsx
  src/components/FolderHeader.tsx
  src/components/FolderList.js
  src/components/FolderList.tsx
  src/components/FolderProfile.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/KebabMenu.tsx
  src/components/LinkCard.tsx
  src/components/LinkForm.tsx
  src/components/Modal.tsx
  src/components/Nav.tsx
  src/components/SearchBar.js
  src/components/SearchBar.tsx
  src/components/api/KakaoShareButton.tsx
  src/components/api/fetchFolderProfileData.tsx
  src/components/api/fetchFolders.tsx
  src/components/api/fetchProfileData.tsx
  src/components/hooks/useFetchCardsData.tsx
  src/components/hooks/useFetchFolders.tsx
  src/components/hooks/useModal.tsx
  src/components/profile.tsx
  src/components/utils.tsx
  src/main.tsx
  src/pages/Folder.tsx
  src/pages/Shared.tsx
  src/styles/FolderList.css
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 매운맛🔥

#259 [최무현] Week12
  src/assets/close.svg
  src/components/App.js
  src/components/Card.js
  src/components/Cards.js
  src/components/Content.js
  src/components/Modal.js
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/pages/Folder.js
  src/pages/Shared.js
Labels: 미완성

#257 [박진아] Week8
  .editorconfig
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/apis.js
  src/components/button/Button.jsx
  src/components/button/button.scss
  src/components/card/Card.jsx
  src/components/folder/AddLink.jsx
  src/components/folder/Folder.jsx
  src/components/folder/FolderListButton.jsx
  src/components/folder/addLink.scss
  src/components/folder/folderListButton.scss
  src/components/modal/AddFolderModal.jsx
  src/components/modal/AddModal.jsx
  src/components/modal/DefaultModal.jsx
  src/components/modal/DeleteFolderModal.jsx
  src/components/modal/DeleteModal.jsx
  src/components/modal/ShareModal.jsx
  src/components/modal/UpdateModal.jsx
  src/components/modal/deleteModal.scss
  src/components/modal/modal.scss
  src/components/modal/shareModal.scss
  src/components/popper/Popper.jsx
  src/components/popper/popper.scss
  src/components/shared/Shared.jsx
  src/components/shared/shared.scss
  src/img/btn-close.svg
  src/img/ic-add-w.svg
  src/img/ic-check.svg
  src/img/ic-facebook.svg
  src/img/ic-kakao.svg
Labels: 매운맛🔥

#254 [권지민] week12
  craco.config.js
  package-lock.json
  package.json
  public/assets/images/icons/closeIconGrey.svg
  src/api/api.js
  src/components/CardTextBox/CardTextBox.js
  src/components/Header/Header.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/index.js
  src/index.js
  src/pages/Folder/Folder.js
  src/reset.css
  src/style/theme/theme.js
  src/utils/filterLinkSearch.js
  src/utils/formatDate.js
  src/utils/isEmailExist.js
  src/utils/timeStamp.js
Labels: 매운맛🔥, 미완성

#251 [조현진] Week12
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/api.js
  src/api.tsx
  src/components/folder/Card.tsx
  src/components/folder/FolderContentCard.tsx
  src/components/folder/FolderList.tsx
  src/components/folder/FolderName.tsx
  src/components/folder/FolderSearchInput.js
  src/components/folder/FolderSection.js
  src/components/folder/FolderSection.tsx
  src/components/folder/Header.tsx
  src/components/folder/LinkAddInput.tsx
  src/components/folder/LinkSearchInput.js
  src/components/folder/LinkSearchInput.tsx
  src/components/folder/Modal.css
  src/components/folder/Modal.tsx
  src/components/folder/ModalContent.js
  src/components/folder/ModalManager.js
  src/components/folder/Modals.js
  src/components/folder/Nav.tsx
  src/components/shared/Header.js
  src/index.tsx
  src/pages/Folder.tsx
  src/pages/Shared.tsx
  src/react-app-env.d.ts
  src/types.tsx
  tsconfig.json
Labels: 순한맛🐑 

#261 [백진영] week12
  public/assets/default_img.png
  public/assets/input_close.png
  src/components/CardContainer/CardContainer.js
  src/components/CardList/CardList.js
  src/components/ContentsArea/ContentsArea.js
  src/components/FolderListArea/FolderListArea.css
  src/components/SearchArea/SearchArea.css
  src/components/SearchArea/SearchArea.js
  src/components/SearchText/SearchText.css
  src/components/SearchText/SearchText.js
Labels: 매운맛🔥, 미완성

#263 [고기호] week12
  .eslintrc
  src/App.jsx
  src/Constants/Constants.js
  src/api/api.js
  src/components/Contents/CardList/CardDescription/CardDescription.jsx
  src/components/Contents/CardList/CardList.jsx
  src/components/Contents/CardSearchBar/CardSearchBar.hook.jsx
  src/components/Contents/CardSearchBar/CardSearchBar.jsx
  src/components/Contents/FolderCollection/FolderCollection.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Hero/Hero.jsx
  src/components/Hero/LinkCreator.jsx/LinkCreator.jsx
  src/components/Hero/ShareDescription/ShareDescription.jsx
  src/components/LinkCreator/LinkCreator.jsx
  src/components/Modal/ChangeFolderName.jsx
  src/components/Modal/CreateFolder.jsx
  src/components/Modal/DeleteFolder.jsx
  src/components/Modal/DeleteLink.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalContent/ModalContentWrapper.jsx
  src/components/Modal/ModalContent/ModalInput.jsx
  src/components/Modal/ModalContent/ModalTitle.jsx
  src/components/Modal/ShareFolder.jsx
  src/components/Modal/UpdateFolder.jsx
  src/components/ShareDescription/ShareDescription.jsx
  src/hooks/useGetFolderListData.jsx
  src/hooks/useGetShareCardList.jsx
  src/hooks/useGetSharePageData.jsx
  src/hooks/useGetSharePageFolderName.jsx
  src/hooks/useGetsharePageIds.jsx
  src/hooks/useSearchBar.jsx
  src/pages/FolderPage.hook.jsx
  src/pages/FolderPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/SharedPage.hook.jsx
  src/pages/SharedPage.jsx
  src/utils/handleModal.js
  src/utils/shareToKakao.js
Labels: 매운맛🔥, 미완성

#222 [이유연] Week8
  package-lock.json
  package.json
  src/App.jsx
  src/GlobalStyles.jsx
  src/assets/banner.png
  src/components/card/Card.jsx
  src/components/card/SelectMenu.jsx
  src/components/folder/ FolderData.jsx
  src/components/folder/AddLink.jsx
  src/components/folder/Content.jsx
  src/components/folder/EditBox.jsx
  src/components/folder/FolderBox.jsx
  src/components/folder/FolderLinkContainer.jsx
  src/components/modal/CommonModal.jsx
  src/components/modal/IconBox.jsx
  src/components/modal/SelectFolder.jsx
  src/components/searchbar/SearchBar.jsx
  src/components/shared/Contents.jsx
  src/pages/Folder.jsx
  src/pages/Home.jsx
  src/pages/Layout.jsx
  src/pages/Shared.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
  src/router/router.js
  src/routes/Folder.jsx
  src/utils/shareKakaoLink.js
Labels: 매운맛🔥

#285 [이재명] Week13
  .gitignore
  components/Folder/Card.tsx
  components/Folder/Folder.tsx
  components/Folder/Footer.tsx
  components/Folder/Header.tsx
  components/Folder/Search.tsx
  components/Folder/Section.tsx
  components/Folder/Sorted.tsx
  components/Folder/Style.tsx
  components/Folder/TimeUtils.tsx
  components/Folder/hooks/useFoldLink.tsx
  components/Folder/modal/Modal.tsx
  components/Folder/modal/ModalStyle.tsx
  components/Shared/Card.jsx
  components/Shared/Footer.jsx
  components/Shared/Header.jsx
  components/Shared/Search.jsx
  components/Shared/Section.jsx
  components/Shared/Shared.jsx
  components/Shared/TimeUtils.jsx
  components/common/EyeIcon.tsx
  components/common/InputStyle.tsx
  components/common/input.tsx
  lib/axios.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/folder/folderApiTs.tsx
  pages/folder/index.tsx
  pages/folder/search/[search].tsx
  pages/folder/type.tsx
  pages/index.tsx
  public/assets/Icons/add.svg
  public/assets/Icons/close.png
  public/assets/Icons/delete.svg
  public/assets/Icons/eye-off.svg
  public/assets/Icons/eye-on.svg
  public/assets/Icons/facebook.svg
  public/assets/Icons/instagram.svg
  public/assets/Icons/kakao.svg
  public/assets/Icons/kebab.svg
  public/assets/Icons/link.svg
  public/assets/Icons/logo.svg
  public/assets/Icons/pen.svg
  public/assets/Icons/search.svg
  public/assets/Icons/share.svg
  public/assets/Icons/star.svg
  public/assets/Icons/twitter.svg
  public/assets/Icons/youtube.svg
  public/assets/Images/tag.png
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  styles/GlobalStyle.ts
  styles/Home.module.css
  styles/Shared.module.css
  styles/globals.css
Labels: 매운맛🔥, 미완성

#283 [조성경] Week13
  .eslintrc.json
  .gitignore
  .prettierrc
  components/AddLink/AddLink.module.css
  components/AddLink/index.tsx
  components/FolderBar/folderbar.module.css
  components/FolderBar/index.tsx
  components/Footer/footer.module.css
  components/Footer/index.tsx
  components/Header/header.module.css
  components/Header/index.tsx
  components/SearchBar/index.tsx
  components/SearchBar/searchbar.module.css
  components/SignHeader/index.tsx
  components/SignHeader/signheader.module.css
  components/atomicComponents/FolderButton/folderbutton.module.css
  components/atomicComponents/FolderButton/index.tsx
  components/atomicComponents/Input/index.tsx
  components/atomicComponents/Input/input.module.css
  components/atomicComponents/Profile/index.tsx
  components/atomicComponents/Profile/profile.module.css
  components/mainhead.tsx
  hooks/useSignUpForm.tsx
  hooks/useTogglePassword.tsx
  libs/client/useMutation.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  public/images/card-default.png
  public/images/check.svg
  public/images/close.svg
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/kebab.svg
  public/images/link.svg
  public/images/linkbrary.svg
  public/images/pen.svg
  public/images/search.svg
  public/images/share.svg
  public/images/signin/eye-off.svg
  public/images/signin/eye-on.svg
  public/images/signin/google.png
  public/images/signin/kakao.png
  public/images/star.svg
  public/images/trash.svg
  public/images/twitter.svg
  public/images/youtube.svg
  styles/folder.module.css
  styles/globals.css
  styles/reset.css
  styles/signin.module.css
  types/sign.ts
  utils/regexPatterns.js
Labels: 미완성

#292 [송상훈] Week13
  .babelrc
  api-access/useGetFolder.js
  api-access/useGetFolders.js
  api-access/useGetLinks.js
  api-access/useGetUser.js
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/_document.jsx
  pages/components/Card/Card.jsx
  pages/components/Card/CardContent/CardContent.jsx
  pages/components/Card/CardImage/CardImage.jsx
  pages/components/Card/EditableCard.jsx
  pages/components/CardList/CardList.jsx
  pages/components/FolderInfo/FolderInfo.jsx
  pages/components/FolderToolBar/AddFolderButton/AddFolderButton.jsx
  pages/components/FolderToolBar/EditButton/EditButtons.jsx
  pages/components/FolderToolBar/FolderToolBar.jsx
  pages/components/FolderToolBar/ToolBarButton/ToolBarButton.jsx
  pages/components/FolderToolBar/constant.js
  pages/components/Footer/Footer.jsx
  pages/components/Footer/constant.js
  pages/components/LinkForm/LinkForm.jsx
  pages/components/NavigationBar/NavigationBar.jsx
  pages/components/NavigationBar/Profile/Profile.jsx
  pages/components/NoLink/NoLink.jsx
  pages/components/SearchBar/SearchBar.jsx
  pages/folder.jsx
  pages/index.jsx
  pages/shared.jsx
  public/images/add.svg
  public/images/card-default.png
  public/images/check.svg
  public/images/close.svg
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/kebab.svg
  public/images/link.svg
  public/images/linkbrary.svg
  public/images/pen.svg
  public/images/search.svg
  public/images/share.svg
  public/images/star.svg
  public/images/trash.svg
  public/images/twitter.svg
  public/images/youtube.svg
  styles/colors.css
  styles/globals.css
  styles/reset.css
  styles/variables.css
  util/axiosInstance.js
  util/constant.js
  util/getElapsedTime.js
  util/mapFolderData.js
  util/mapLinksData.js
  util/useAsync.js
  util/useEffectOnce.js
Labels: 매운맛🔥, 미완성

#304 [오영곤] Week14
  package-lock.json
  package.json
  public/images/eye_on.svg
  public/images/google_login.svg
  public/images/kakao_login.svg
  src/api/api.ts
  src/app/(home)/page.tsx
  src/app/(navigatorBar)/NavigatorBar.tsx
  src/app/contents.css
  src/app/folder/(folderContents)/FolderContents.tsx
  src/app/folder/(folderContents)/FolderGroup.tsx
  src/app/folder/[id]/layout.tsx
  src/app/folder/[id]/page.tsx
  src/app/header.css
  src/app/layout.tsx
  src/app/shared/(sharedContents)/SharedContents.tsx
  src/app/shared/(sharedContents)/SharedHeader.tsx
  src/app/shared/layout.tsx
  src/app/shared/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/cardList/KebebPopover.tsx
  src/components/cardList/cardList.css
  src/components/cardList/cardList.tsx
  src/components/login/Login.tsx
  src/components/login/LoginForm.tsx
  src/components/login/login.css
  src/components/modal/BaseModal.tsx
  src/components/modal/modalType/DeleteModal.tsx
  src/components/modal/modalType/ShareModal.tsx
  src/components/searchBar/SearchBar.tsx
  src/components/searchBar/searchBar.css
  src/components/textInput/TextInput.tsx
  src/components/textInput/textInput.css
  src/utils/calculateDate.ts
Labels: 매운맛🔥

#295 [이치현] Week14
  app/page.tsx
  app/signin/index.module.css
  app/signin/page.tsx
  app/signup/index.module.css
  app/signup/page.tsx
  components/BigGoMainLogo/index.tsx
  components/BigGoMainLogo/linkbrary.svg
  components/LoginForm/index.module.css
  components/LoginForm/index.tsx
  components/LoginSocialBox/index.module.css
  components/LoginSocialBox/index.tsx
  components/SignupForm/index.module.css
  components/SignupForm/index.tsx
  components/SignupSocialBox/index.module.css
  components/SignupSocialBox/index.tsx
  images/eye-off.svg
  images/eye-on.svg
  images/googleIcon.svg
  images/kakaotalkIcon.svg
  next.config.js
  package-lock.json
  package.json
Labels: 매운맛🔥

#301 [김범주]Week14
  global.d.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/api.ts
  pages/folder.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  pages/test.tsx
  src/components/Input/Input.module.css
  src/components/Input/Input.tsx
  src/components/footer/LinkString/LinkString.tsx
  src/components/footer/Sns/Sns.tsx
  src/components/header/AddLink/AddLink.tsx
  src/components/header/Folder/Folder.tsx
  src/components/header/Nav/Nav.tsx
  src/components/header/Profile/Profile.tsx
  src/components/section/BaseModal/BaseModal.tsx
  src/components/section/Card/Card.tsx
  src/components/section/DropDown/DropDown.tsx
  src/components/section/EditOption/EditOption.tsx
  src/components/section/FolderList/FolderList.tsx
  src/components/section/FolderListButton/FolderListButton.tsx
  src/components/section/Search/Search.tsx
  src/hooks/useIntersectionObserver.ts
  styles/reset.css
  styles/signin.module.css
  styles/signup.module.css
  tsconfig.json
Labels: 미완성, 순한맛🐑 

#302 [박지용] week14
  components/atomicComponents/kebab/Kebab.tsx
  components/atomicComponents/kebab/kebab.module.css
  components/atomicComponents/loginButton/index.tsx
  components/atomicComponents/loginButton/loginButton.module.css
  components/atomicComponents/loginInput/index.tsx
  components/atomicComponents/loginInput/loginInput.module.css
  components/atomicComponents/logoText/index.tsx
  components/atomicComponents/logoText/logoText.module.css
  components/atomicComponents/modal/ModalMessage.module.css
  components/atomicComponents/modal/ModalMessage.tsx
  components/atomicComponents/modal/SnsIcon.tsx
  components/atomicComponents/modal/SnsShareModal.tsx
  components/atomicComponents/snsLogin/index.tsx
  components/atomicComponents/snsLogin/snsLogin.module.css
  components/moduleComponents/CardSection/Card.tsx
  components/moduleComponents/CardSection/CardSection.module.css
  components/moduleComponents/CardSection/CardSection.tsx
  components/moduleComponents/CardSection/Search.tsx
  components/moduleComponents/FooterSection/Footer.module.css
  components/moduleComponents/FooterSection/Footer.tsx
  components/moduleComponents/HeaderSection/Bookmark.tsx
  components/moduleComponents/HeaderSection/HeaderSection.module.css
  components/moduleComponents/HeaderSection/HeaderSection.tsx
  components/moduleComponents/HeaderSection/LinkAdd.module.css
  components/moduleComponents/HeaderSection/LinkAdd.tsx
  components/moduleComponents/HeaderSection/Profile.tsx
  components/moduleComponents/folder/FolderActionBtn.module.css
  components/moduleComponents/folder/FolderActionBtn.tsx
  components/moduleComponents/folder/FolderList.module.css
  components/moduleComponents/folder/FolderListBtn.tsx
  components/moduleComponents/signIn/index.tsx
  components/moduleComponents/signIn/signin.module.css
  components/moduleComponents/signUp/index.tsx
  components/moduleComponents/signUp/signup.module.css
  hook/useEmailDuplicate.ts
  hook/useSignIn.ts
  hook/useSignUp.ts
  libs/axios.ts
  next.config.js
  package-lock.json
  package.json
  pages/404.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/image/eyeoff.svg
  public/image/eyeon.svg
  public/image/google.png
  public/image/index.ts
  public/image/kakaotalk.svg
  src/utils/regexPatterns.ts
  src/utils/timeUtils.ts
  styles/signUp.module.css
  styles/signin.module.css
  tsconfig.json
  types/Types.ts
Labels: 매운맛🔥

#307 [이시열] week14
  app/(home)/components/HomeBody.tsx
  app/(home)/layout.tsx
  app/(home)/page.tsx
  app/components/Sign/Sign.tsx
  app/components/Sign/SignForm.tsx
  app/components/input/Input.tsx
  app/folder/layout.tsx
  app/layout.tsx
  app/shared/layout.tsx
  app/signin/page.tsx
  app/signup/Signup.tsx
  app/signup/page.tsx
  package-lock.json
  package.json
  public/google-logo.svg
  public/kakao-logo.svg
Labels: 매운맛🔥, 미완성

#311 [김성훈] Week14
  app/(home)/page.tsx
  app/signin/page.module.css
  app/signin/page.tsx
  app/signup/page.module.css
  app/signup/page.tsx
  components/Input/Input.css
  components/Input/Input.tsx
  components/Input/LoginForm.tsx
  components/LoginBox/LoginBox.module.css
  components/LoginBox/LoginBox.tsx
  components/LoginForm/LoginForm.module.css
  components/LoginForm/LoginForm.tsx
  components/SignupBox/SignupBox.module.css
  components/SignupBox/SignupBox.tsx
  components/api/fetchCheckEmail.tsx
  components/api/fetchLogin.tsx
  components/api/fetchSignUp.tsx
  package-lock.json
  package.json
  public/images/google.svg
  public/images/kakao.svg
  public/images/logo2.svg
Labels: 매운맛🔥

#303 [고기호] week14
  .eslintrc.json
  .nvmrc
  Constants/Constants.ts
  components/Sign/EmailInput.tsx
  components/Sign/Form.hook.tsx
  components/Sign/Form.tsx
  components/Sign/Header.tsx
  components/Sign/PasswordInput.tsx
  components/Sign/SnsLogin.tsx
  components/SignInput/PasswordInput.tsx
  components/SignInput/SignInput.tsx
  hooks/useGetPathname.tsx
  interfaces/index.ts
  package-lock.json
  package.json
  pages/_document.tsx
  pages/index.tsx
  pages/shared/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/images/sign_google_background.svg
  public/images/sign_google_icon.png
  public/images/sign_kakao_background.svg
  public/images/sign_kakao_icon.svg
  public/images/sign_logo.svg
  tsconfig.json
  types/index.ts
  utils/postFetch.ts
  utils/setAccessToken.ts
  utils/shareToKakao.ts
Labels: 매운맛🔥

#310 [김민교]Week14
  .env
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/api.ts
  pages/api/hello.ts
  pages/folder.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  pages/test.tsx
  src/components/footer/FooterLinks/FooterLinks.tsx
  src/components/footer/LinkLogo/LinkLogo.tsx
  src/components/footer/LinkString/LinkString.module.css
  src/components/footer/LinkString/LinkString.tsx
  src/components/footer/Sns/Sns.module.css
  src/components/footer/Sns/Sns.tsx
  src/components/header/AddLink/AddLink.module.css
  src/components/header/AddLink/AddLink.tsx
  src/components/header/Folder/Folder.module.css
  src/components/header/Folder/Folder.tsx
  src/components/header/Nav/Nav.module.css
  src/components/header/Nav/Nav.tsx
  src/components/header/Profile/Profile.module.css
  src/components/header/Profile/Profile.tsx
  src/components/input/input.module.css
  src/components/input/input.tsx
  src/components/section/BaseModal/BaseModal.module.css
  src/components/section/BaseModal/BaseModal.tsx
  src/components/section/Card/Card.module.css
  src/components/section/Card/Card.tsx
  src/components/section/DropDown/DropDown.module.css
  src/components/section/DropDown/DropDown.tsx
  src/components/section/EditOption/EditOption.module.css
  src/components/section/EditOption/EditOption.tsx
  src/components/section/FolderList/FolderList.module.css
  src/components/section/FolderList/FolderList.tsx
  src/components/section/FolderListButton/FolderListButton.module.css
  src/components/section/FolderListButton/FolderListButton.tsx
  src/components/section/Search/Search.module.css
  src/components/section/Search/Search.tsx
  src/hooks/useIntersectionObserver.ts
  src/utils/timeElapsedCalculate.ts
  styles/index.css
  styles/page.module.css
  styles/reset.css
  styles/signin.module.css
  styles/signup.module.css
Labels: 미완성, 순한맛🐑 
