Repository codeit-bootcamp-frontend/3-Weekly-Mission, pull requests merged in 2024-03, with the labels that each got.

#320 [심은주] Week14
  api/getFolderLinks.ts
  api/getFolderUser.ts
  components/Cardlist/index.tsx
  components/FolderComponents/FolderCard/index.tsx
  components/FolderComponents/FolderCardlist/index.tsx
  components/FolderComponents/FolderContent/index.tsx
  components/FolderComponents/FolderFilterKeywords/index.tsx
  components/FolderComponents/FolderFilterKeywords/style.module.css
  components/FolderComponents/FolderTitlebar/index.tsx
  components/FolderUtilsButtons/index.tsx
  components/FolderUtilsButtons/style.module.css
  components/Footer/index.tsx
  components/Header/index.tsx
  components/LoginCTA/index.tsx
  components/LoginCTA/style.module.css
  components/Searchbar/index.tsx
  components/SharedComponents/SharedCard/index.tsx
  components/SharedComponents/SharedCardlist/index.tsx
  components/SharedComponents/SharedContent/index.tsx
  components/SharedComponents/SharedTitlebar/index.tsx
  components/SharedComponents/SharedTitlebar/style.module.css
  components/UserProfile/index.tsx
  components/draft/Input/Input.module.css
  components/draft/Input/Input.tsx
  components/draft/SignInForm/SignInForm.jsx
  components/draft/SignInForm/SignInForm.module.css
  components/draft/SignUpForm/SignupForm.jsx
  components/draft/SignUpForm/SignupForm.module.css
  next.config.js
  pages/_document.tsx
  pages/folder.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  styles/Home.module.css
  styles/card.module.css
  styles/cardlist.module.css
  styles/titlebar.module.css
  types/index.d.ts
  utils/isMatchSearchKeyword.ts
Labels: 미완성

#313 [박준수] Week14
  .eslintrc.json
  api/api.ts
  components/FolderManagementMenu/index.tsx
  components/FolderMenu/index.tsx
  components/Input/index.tsx
  components/Input/style.module.css
  components/SignPages/SignHeader/index.tsx
  components/SignPages/SignHeader/styles.module.css
  components/SignPages/SigninForm/index.tsx
  components/SignPages/SigninForm/styles.module.css
  components/SignPages/SignupForm/index.tsx
  components/SignPages/SignupForm/styles.module.css
  components/SignPages/SocialSign/index.tsx
  components/SignPages/SocialSign/styles.module.css
  constants/constants.ts
  constants/error.ts
  constants/regex.ts
  constants/time.ts
  constants/url.ts
  package-lock.json
  package.json
  pages/folder.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/images/eye-off.svg
  public/images/eye-on.svg
  public/images/google.png
  public/images/kakaotalk.png
  styles/sign.module.css
  types/Common.ts
  utils/formatDate.ts
Labels: 매운맛🔥

#318 [송상훈] week14
  hooks/useGetFolder.js
  hooks/useGetFolders.js
  hooks/useGetLinks.js
  hooks/useGetUser.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/components/Card/EditableCard.jsx
  pages/components/CardList/CardList.jsx
  pages/components/CardList/FolderPageCardList/FolderPageCardList.jsx
  pages/components/FolderToolBar/AddFolderButton/AddFolderButton.jsx
  pages/components/FolderToolBar/EditButton/EditButtons.jsx
  pages/components/FolderToolBar/FolderToolBar.jsx
  pages/components/FolderToolBar/constant.js
  pages/components/Footer/Footer.jsx
  pages/components/LinkForm/LinkForm.jsx
  pages/components/Modal/AddLinkModal/AddLinkModal.jsx
  pages/components/Modal/DeleteModal/DeleteModal.jsx
  pages/components/Modal/InputModal/InputModal.jsx
  pages/components/Modal/ShareModal/ShareModal.jsx
  pages/components/ModalContents/ModalContainer/ModalContainer.jsx
  pages/components/ModalContents/ModalContentBox/ModalContentBox.jsx
  pages/components/ModalContents/ModalContentButton/ModalContentButton.jsx
  pages/components/ModalContents/ModalContentInput/ModalContentInput.jsx
  pages/components/ModalContents/ModalContentTitle/ModalContentTitle.jsx
  pages/components/ModalContents/ModalDescription/ModalDescription.jsx
  pages/components/ModalContents/ModalFolderItem/ModalFolderItem.jsx
  pages/components/NavigationBar/NavigationBar.jsx
  pages/components/Popover/Popover.jsx
  pages/components/Portal/Portal.jsx
  pages/folder.jsx
  pages/shared.jsx
  public/images/Kakao.svg
  public/images/Weekly Mission[3기] (Copy).zip
  util/constant.js
  util/copyToClipboard.js
  util/getElapsedTime.js
  util/useBackgroundClick.js
  util/useKakaoSdk.js
Labels: 매운맛🔥, 미완성

#317 [조예진] week14
  @types/api/interface.ts
  @types/global.d.ts
  api/api.ts
  components/Button/Button.module.css
  components/Button/Button.tsx
  components/CardList/Card/Card.module.css
  components/CardList/Card/Card.tsx
  components/CardList/CardList.module.css
  components/CardList/CardList.tsx
  components/Content/Content.tsx
  components/Folder/FolderList.tsx
  components/Header/Header.tsx
  components/Input/Input.module.css
  components/Input/Input.tsx
  components/Modal/Modal.module.css
  components/Modal/Modal.tsx
  components/Modal/SelectFolderBox.tsx
  components/Modal/SelectFolderItem.tsx
  components/Modal/ShareIconBox.tsx
  components/PopOver/PopOver.module.css
  components/PopOver/PopOver.tsx
  components/SignForm/SignForm.module.css
  components/SignForm/SignForm.tsx
  components/SignInForm/SignInForm.jsx
  components/SignInForm/SignInForm.module.css
  components/SignUpForm/SignupForm.jsx
  components/SocialSignBox/SocialSignBox.module.css
  components/SocialSignBox/SocialSignBox.tsx
  constants/constant.ts
  constants/sign.ts
  hooks/useFolderData.ts
  hooks/useLinkDataByFolderId.ts
  hooks/useSampleFolderData.ts
  hooks/useUserData.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder.tsx
  pages/sign.module.css
  pages/signin.tsx
  pages/signup.tsx
  tsconfig.json
  utils/registerOptions.tsx
Labels: 매운맛🔥

#299 [권지민] Week 14
  .gitignore
  api/getFolderData.ts
  api/getFolderNameData.ts
  api/getUserData.ts
  api/postEmailCheck.ts
  api/postSignIn.ts
  api/postSignUp.ts
  components/Layout.tsx
  components/portal/portal.tsx
  components/ui/atoms/folder-sorting/FolderSortingList.tsx
  components/ui/atoms/input/Input.tsx
  components/ui/atoms/modal/ModalAddFolder.tsx
  components/ui/atoms/modal/ModalContainer.module.css
  components/ui/atoms/modal/ModalContainer.tsx
  components/ui/atoms/modal/context/modalProvider.tsx
  components/ui/molecules/navigation-bar/NavigationBar.module.css
  components/ui/molecules/navigation-bar/NavigationBar.tsx
  constants/api/api.ts
  constants/messages/error.ts
  constants/regex/regex.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder/index.tsx
  pages/share/[folderid].tsx
  pages/share/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/assets/images/icons/eye-off-icon.svg
  public/assets/images/icons/eye-on-icon.svg
  public/assets/images/icons/google-login-icon.svg
  public/assets/images/icons/kakao-login-icon.svg
  styles/Home.module.css
  styles/global.module.css
  styles/sign.module.css
  types/auth/userType.ts
  types/folderNameType.ts
  types/inputType.ts
  types/selectedFolderNameInfo.ts
  utils/date/formateDate.ts
  utils/date/timeStamp.ts
  utils/regex/checkRegex.ts
  utils/scroll/checkCurrentY.ts
Labels: 순한맛🐑 

#308 [노진석] week14
  apis/api.ts
  apis/axios.ts
  components/Card/Card.tsx
  components/CtaButton/CtaButton.tsx
  components/FloatingActionButton/FloatingActionButton.tsx
  components/FolderListButton/FolderListButton.tsx
  components/FolderNameLine/FolderNameLine.tsx
  components/Footer/Footer.tsx
  components/Kebab/Kebab.tsx
  components/LinkAddForm/LinkAddForm.tsx
  components/LinkSearchForm/LinkSearchForm.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalAddLink/AddFolderListBox.tsx
  components/Modal/ModalAddLink/ModalAddLink.tsx
  components/Modal/ModalDelete.tsx
  components/Modal/ModalShare/ModalShare.tsx
  components/Navbar/Navbar.tsx
  components/SignInput/SignInput.tsx
  components/SocialSignBox/SocialSignBox.tsx
  components/Spinner/Spinner.tsx
  constants/sign.ts
  next.config.js
  package-lock.json
  package.json
  pages/folder.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  pages/test.tsx
  public/img/index.ts
  public/img/signin-kakao-bg.svg
  types/dataTypes.ts
  types/modalTypes.ts
  types/types.ts
  utils/signValidator.ts
Labels: 매운맛🔥

#325 [고현우] week14
  components/formInput/emailInput/EmailInput.module.scss
  components/formInput/emailInput/EmailInput.tsx
  components/formInput/passwordInput/PasswordInput.module.scss
  components/formInput/passwordInput/PasswordInput.tsx
  lib/api.ts
  next.config.js
  pages/api/hello.ts
  pages/folder/folderMenu/folderSelector/FolderSelector.tsx
  pages/folder/index.tsx
  pages/folder/modal/modalType/shareFolder.tsx/ShareFolder.tsx
  pages/index.tsx
  pages/signin/form/SigninForm.module.scss
  pages/signin/form/SigninForm.tsx
  pages/signin/header/SigninHeader.module.scss
  pages/signin/header/SigninHeader.tsx
  pages/signin/index.tsx
  pages/signup/form/SignupForm.module.scss
  pages/signup/form/SignupForm.tsx
  pages/signup/header/SignupHeader.module.scss
  pages/signup/header/SignupHeader.tsx
  pages/signup/index.tsx
  public/assets/eye-off.svg
  public/assets/eye-on.svg
  public/assets/google.svg
  public/assets/kakao.png
  styles/globals.scss
  styles/signin.module.scss
  styles/signup.module.scss
Labels: 매운맛🔥

#305 [최무현] Week14
  api.ts
  components/Card.tsx
  components/Header.module.css
  components/accountPage/AccountHeader.tsx
  components/accountPage/Input.module.css
  components/accountPage/Input.tsx
  components/accountPage/SigninForm.tsx
  components/accountPage/SignupForm.tsx
  components/accountPage/SocialLoginForm.tsx
  components/modals/Modal.tsx
  components/modals/ShareModal.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/google-icon.svg
  public/kakao-icon.svg
  styles/accountPage.module.css
  styles/global.css
Labels: 매운맛🔥

#327 [김범주]Week15
  pages/api/api.ts
  pages/folder/[folderId].tsx
  pages/folder/index.tsx
  pages/shared/[folderId].tsx
  pages/signin.tsx
  pages/signup.tsx
  src/components/Input/Input.tsx
  src/components/header/AddLink/AddLink.tsx
  src/components/header/Folder/Folder.tsx
  src/components/header/Nav/Nav.tsx
  src/components/header/Profile/Profile.tsx
  src/components/section/Card/Card.tsx
  src/components/section/EditOption/EditOption.tsx
  src/components/section/FolderList/FolderList.tsx
  src/components/section/FolderListButton/FolderListButton.tsx
  src/hooks/useIntersectionObserver.ts
  src/state/atoms.ts
Labels: 미완성, 순한맛🐑 

#329 [조현진] Week15
  api/signApi.tsx
  components/common/EmailInput.module.scss
  components/common/EmailInput.tsx
  components/common/Input.tsx
  components/common/PasswordInput.tsx
  components/common/input.module.scss
  components/folder/Modal.tsx
  components/signin/SignInForm.tsx
  components/signup/ConfirmPasswordInput.module.scss
  components/signup/ConfirmPasswordInput.tsx
  components/signup/SignUpForm.tsx
  package-lock.json
  package.json
  utils/validationSchemas.ts
Labels: 순한맛🐑 

#333 [노진석] week15
  apis/api.ts
  apis/axios.ts
  apis/user.ts
  components/Card/Card.tsx
  components/CardList/CardList.tsx
  components/FolderListButton/FolderListButton.tsx
  components/Kebab/Kebab.tsx
  components/LinkSearchForm/LinkSearchForm.tsx
  components/Modal/Modal.tsx
  components/Modal/ModalAddLink/AddFolderListBox.tsx
  components/Modal/ModalAddLink/ModalAddLink.tsx
  components/Modal/ModalShare/ModalShare.tsx
  components/Navbar/Navbar.tsx
  hooks/useUserChange.tsx
  pages/_app.tsx
  pages/folder/[folderId]/index.tsx
  pages/folder/index.tsx
  pages/shared/[folderId]/index.tsx
  pages/signin.tsx
  pages/signup.tsx
  types/dataTypes.ts
  types/userType.ts
  utils/kakaoShare.ts
Labels: 매운맛🔥

#334 [이재명] Week15
  api/axiosInstance.tsx
  api/getAllCard.tsx
  api/getFolderList.tsx
  api/getSignIn.tsx
  api/getSignUp.tsx
  api/getToken.tsx
  components/Folder/FolderMake/FolderMake.tsx
  components/common/Nav/Nav.tsx
  components/sign/SignForm/SignForm.tsx
  contexts/AuthProvider.tsx
  hooks/useAuth.tsx
  package-lock.json
  package.json
  pages/Home.module.scss
  pages/Home.style.tsx
  pages/_app.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  utils/calcDate.tsx
Labels: 매운맛🔥, 미완성

#323 [오영곤] Week15
  next.config.mjs
  request.http
  src/api/api.ts
  src/app/(navigatorBar)/NavigatorBar.tsx
  src/app/api/cookies/route.ts
  src/app/folder/(folderContents)/FolderContainer.tsx
  src/app/folder/(folderContents)/FolderContents.tsx
  src/app/folder/(folderContents)/FolderGroup.tsx
  src/app/folder/(folderContents)/HeadlessClient.tsx
  src/app/folder/[id]/page.tsx
  src/app/folder/layout.tsx
  src/app/folder/page.tsx
  src/app/shared/(sharedContents)/SharedHeader.tsx
  src/app/shared/[id]/layout.tsx
  src/app/shared/[id]/page.tsx
  src/app/shared/page.tsx
  src/components/login/Login.tsx
  src/components/login/LoginForm.tsx
  src/components/modal/modalType/DeleteModal.tsx
  src/components/modal/modalType/ShareModal.tsx
  src/utils/shareKakao.ts
Labels: 매운맛🔥

#328 [윤해용] Week14
  components/AuthButton/AuthButton.module.css
  components/AuthButton/index.tsx
  components/AuthInput/AuthInput.module.css
  components/AuthInput/index.tsx
  components/Logo/Logo.module.css
  components/Logo/index.tsx
  components/SocialLogin/SocialLogin.module.css
  components/SocialLogin/index.tsx
  lib/api.ts
  lib/types.ts
  lib/utils.ts
  package-lock.json
  package.json
  pages/folder.tsx
  pages/index.tsx
  pages/signin.tsx
  pages/signup.tsx
  styles/signin.module.css
Labels: 순한맛🐑 
