Repository codeit-bootcamp-frontend/3-Weekly-Mission, pull requests merged in 2024-01, with the labels that each got.

#176 [김범주]Week6
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Card.css
  src/Folder.css
  src/Nav.css
  src/Search.css
  src/api.js
  src/components/App.js
  src/components/Card.js
  src/components/Folder.js
  src/components/Nav.js
  src/components/Search.js
  src/images/Search.png
  src/images/eye-off.svg
  src/images/eye-on.svg
  src/images/facebook.svg
  src/images/google.png
  src/images/hero.png
  src/images/image1.png
  src/images/image2.png
  src/images/image3.png
  src/images/image4.png
  src/images/instagram.svg
  src/images/kakaotalk.png
  src/images/logo.svg
  src/images/twitter.svg
  src/images/youtube.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/reset.css
  src/setupTests.js
  src/timeDifferenceCalculate.js
Labels: 미완성, 순한맛🐑 

#187 [이주영]Week6
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  reset.css
  src/App.css
  src/App.js
  src/App.test.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/searchbar/Searchbar.css
  src/components/searchbar/Searchbar.js
  src/components/section/Section.css
  src/components/section/Section.js
  src/components/user_profile/UserProfile.css
  src/components/user_profile/UserProfile.js
  src/images/Avatar.png
  src/images/Search.png
  src/images/facebook.png
  src/images/instagram.png
  src/images/logo.png
  src/images/noImage.svg
  src/images/profile.png
  src/images/twitter.png
  src/images/youtube.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/date.js
Labels: 매운맛🔥

#180 [최무현] Week6
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/back_dog.png
  src/assets/bed.png
  src/assets/building_sky.png
  src/assets/car_image.png
  src/assets/facebook_icon.svg
  src/assets/instagram_icon.svg
  src/assets/logo.svg
  src/assets/myprofile.svg
  src/assets/myprofile_bg.svg
  src/assets/no-img-logo.svg
  src/assets/orange_light.png
  src/assets/search.svg
  src/assets/smile_face.svg
  src/assets/some_line.png
  src/assets/table_chair.png
  src/assets/three_light.png
  src/assets/twitter_icon.svg
  src/assets/yellow_dog.png
  src/assets/youtube_icon.svg
  src/assets/즐겨찾기.png
  src/components/App.css
  src/components/App.js
  src/components/Banner.css
  src/components/Banner.js
  src/components/Card.css
  src/components/Card.js
  src/components/Cards.css
  src/components/Cards.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#171 [조성경] week6
  .eslintrc.js
  .gitignore
  .prettierrc
  babel.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/api/folderApi.js
  src/api/userApi.js
  src/assets/images/index/Search.svg
  src/assets/images/index/default-thumbnail.png
  src/assets/images/index/facebook.svg
  src/assets/images/index/hero.png
  src/assets/images/index/image7.jpg
  src/assets/images/index/instagram.svg
  src/assets/images/index/landing-image.webp
  src/assets/images/index/logo.svg
  src/assets/images/index/twitter.svg
  src/assets/images/index/white.svg
  src/assets/images/index/youtube.svg
  src/assets/styles/color.css
  src/assets/styles/index.css
  src/assets/styles/reset.css
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/header/headerNavProfile.js
  src/components/index/mainCard.js
  src/hooks/useFolderState.js
  src/hooks/useProfileState.js
  src/logo.svg
  src/pages/indexPage.js
  src/utils/api.js
  src/utils/dateUtils.js
Labels: 매운맛🔥, 미완성

#167 [권지민] Week 6
  public/assets/images/SearchIcon.png
  public/assets/images/facebook.png
  public/assets/images/instagram.png
  public/assets/images/logo.svg
  public/assets/images/no_image.svg
  public/assets/images/twitter.png
  public/assets/images/youtube.png
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/api/api.js
  src/common.css
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Input/InputType.js
  src/components/Input/SearchBarStyle.css
  src/components/Input/SearchBarStyle.js
  src/components/ProfileImage/ProfileImage.css
  src/components/ProfileImage/ProfileImage.js
  src/components/UserInfo/UserInfo.css
  src/components/UserInfo/UserInfo.js
  src/constans.js
  src/index.js
  src/pages/Folder/Folder.css
  src/pages/Folder/Folder.js
  src/reset.css
  src/util.js
Labels: 미완성, 순한맛🐑 

#172 [박준용] Week6
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/Search.svg
  src/assets/faceBook.svg
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Black.woff2
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard-Thin.woff
  src/assets/fonts/Pretendard-Thin.woff2
  src/assets/instagram.svg
  src/assets/kebab.svg
  src/assets/logo.svg
  src/assets/star.svg
  src/assets/twtter.svg
  src/assets/url.js
  src/assets/youtube.svg
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Main/Main.css
  src/components/Main/Main.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Section/Section.css
  src/components/Section/Section.js
  src/font.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/TimeDiffChecker/TimeDiffChecker.js
  src/utils/TodayIs/TodayIs.js
Labels: 매운맛🔥

#184 [조형민] week6
  .gitignore
  package-lock.json
  package.json
  public/images/logo/landing-logo.svg
  public/images/shared/magnifier.svg
  public/images/shared/no-image.svg
  public/images/shared/shared-avatar.svg
  public/images/social-media/facebook.svg
  public/images/social-media/instagram.svg
  public/images/social-media/twitter.svg
  public/images/social-media/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/api/getProfileData.js
  src/api/getUserFolders.js
  src/api/instance/instance-api.js
  src/components/ui/atoms/button/Button.css
  src/components/ui/atoms/button/Button.jsx
  src/components/ui/molecules/card/linkCard/CardCover.jsx
  src/components/ui/molecules/card/linkCard/CardImage.jsx
  src/components/ui/molecules/card/linkCard/CreatedAt.jsx
  src/components/ui/molecules/card/linkCard/Description.jsx
  src/components/ui/molecules/card/linkCard/TimeElapsed.jsx
  src/components/ui/molecules/card/linkCard/context/card-provider.jsx
  src/components/ui/molecules/card/linkCard/index.js
  src/global.css
  src/hooks/useInput.js
  src/index.css
  src/index.js
  src/lib/utils/time/formatDate.js
  src/lib/utils/time/getTimeDiff.js
  src/pages/shared-page/Shared.css
  src/pages/shared-page/Shared.page.jsx
  src/pages/shared-page/comp/article/Article.css
  src/pages/shared-page/comp/article/Article.jsx
  src/pages/shared-page/comp/article/comp/card-container/CardContainer.css
  src/pages/shared-page/comp/article/comp/card-container/CardContainer.jsx
  src/pages/shared-page/comp/article/comp/card-container/comp/card/Card.css
  src/pages/shared-page/comp/article/comp/card-container/comp/card/Card.jsx
  src/pages/shared-page/comp/article/comp/search-bar/SearchBar.css
  src/pages/shared-page/comp/article/comp/search-bar/SearchBar.jsx
  src/pages/shared-page/comp/banner/Banner.css
  src/pages/shared-page/comp/banner/Banner.jsx
  src/shared/layout/header&footer/HeaderAndFooter.jsx
  src/shared/layout/header&footer/comp/footer/Footer.css
  src/shared/layout/header&footer/comp/footer/Footer.jsx
  src/shared/layout/header&footer/comp/header/Header.css
  src/shared/layout/header&footer/comp/header/Header.jsx
  src/shared/layout/header&footer/comp/header/comp/login-button/LoginButton.jsx
  src/shared/layout/header&footer/comp/header/comp/login-success-profile/LoginSuccessProfile.css
  src/shared/layout/header&footer/comp/header/comp/login-success-profile/LoginSuccessProfile.jsx
  src/style/color.css
  src/style/reset.css
Labels: 매운맛🔥

#182 [김성훈] Week6
  public/FAQ.html
  public/Privacy.html
  public/favicon.ico
  public/images/Avatar.png
  public/images/Search.png
  public/images/facebook.png
  public/images/instagram.png
  public/images/logo.png
  public/images/noimageicon.png
  public/images/twitter.png
  public/images/youtube.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Cardlist.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Nav.js
  src/components/api/CardContainer.js
  src/components/api/profile.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Cardlist.css
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/Nav.css
Labels: 매운맛🔥

#177 [이재명] Week6
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/api.js
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/Section.css
  src/components/Section.jsx
  src/components/color.css
  src/components/utils.jsx
  src/images/facebook.svg
  src/images/instagram.svg
  src/images/login.png
  src/images/logo.svg
  src/images/twitter.svg
  src/images/wrong-link.png
  src/images/youtube.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#170 [이시열] Week6
  .eslintrc.json
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/asset/SearchIcon.svg
  src/asset/akar-icons_facebook-fill.svg
  src/asset/akar-icons_twitter-fill.svg
  src/asset/akar-icons_youtube-fill.svg
  src/asset/ant-design_instagram-filled.svg
  src/asset/default-image.svg
  src/asset/logo.svg
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/Folder/FolderArea.css
  src/components/Folder/FolderArea.jsx
  src/components/Folder/FolderInfo.css
  src/components/Folder/FolderInfo.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Navbar/NavProfile.css
  src/components/Navbar/NavProfile.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/constants/api.js
  src/index.css
  src/index.js
  src/index.jsx
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/calculateTime.js
  src/utils/getFetchRequest.js
Labels: 매운맛🔥

#190 [송상훈] week6
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Footer/Footer.css
  src/Footer/Footer.js
  src/Header/Header.css
  src/Header/Header.js
  src/Main/Main.css
  src/Main/Main.js
  src/Section/Card/Card.css
  src/Section/Card/Card.js
  src/Section/Search/Search.css
  src/Section/Search/Search.js
  src/Section/Section.css
  src/Section/Section.js
  src/Section/TimeDiffChecker/TImeDiffChecker.js
  src/images/Search.svg
  src/images/codeit.svg
  src/images/facebook.svg
  src/images/instagram.svg
  src/images/kebab.svg
  src/images/logo.svg
  src/images/myprofile.svg
  src/images/star.svg
  src/images/twitter.svg
  src/images/youtube.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 미완성

#165 [조현진] Week6
  .vs/slnx.sqlite
  .vs/slnx.sqlite-journal
  public/favicon.ico
  public/imgs/01_모코코콘1_16_백색모코코_물음표.png
  public/imgs/akar-icons_facebook-fill.png
  public/imgs/akar-icons_twitter-fill.png
  public/imgs/akar-icons_youtube-fill.png
  public/imgs/ant-design_instagram-filled.png
  public/imgs/logo.png
  public/imgs/로그인.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/DateUtils.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Section.css
  src/components/Section.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/reset.css
Labels: 순한맛🐑 

#181 [백진영] Week6
  package-lock.json
  package.json
  public/assets/Avatar.png
  public/assets/Search.png
  public/assets/icon_google.png
  public/assets/icon_kakao.png
  public/assets/icons_facebook.png
  public/assets/icons_instagram.png
  public/assets/icons_twitter.png
  public/assets/icons_youtube.png
  public/assets/image 7.png
  public/assets/logo.png
  public/assets/profile img.png
  src/App.css
  src/App.js
  src/App.test.js
  src/CardContainer/CardContainer.css
  src/CardContainer/CardContainer.js
  src/ContentsArea/ContentsArea.css
  src/ContentsArea/ContentsArea.js
  src/Folder/Folder.css
  src/Folder/Folder.js
  src/api/api.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/SearchArea/SearchArea.css
  src/components/SearchArea/SearchArea.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/setPassedTime.js
Labels: 매운맛🔥

#185 [박지용] week6
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/Api.js
  src/App.css
  src/App.js
  src/App.test.js
  src/Footer/Footer.css
  src/Footer/Footer.js
  src/Header/Bookmark.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Profile.js
  src/Main/Card.js
  src/Main/Main.css
  src/Main/Main.js
  src/Main/Search.js
  src/image/codeit.svg
  src/image/facebook.svg
  src/image/glass.svg
  src/image/instagram.svg
  src/image/logo.svg
  src/image/myprofile.svg
  src/image/star.jpg
  src/image/twitter.svg
  src/image/youtube.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/shared.js
Labels: 매운맛🔥, 미완성

#188 [윤해용] Week6
  README.md
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/eye-off.svg
  src/assets/eye-on.svg
  src/assets/facebook.svg
  src/assets/google.png
  src/assets/hero.png
  src/assets/image1.png
  src/assets/image2.png
  src/assets/image3.png
  src/assets/image4.png
  src/assets/instagram.svg
  src/assets/kakao.svg
  src/assets/logo.svg
  src/assets/no-image.png
  src/assets/search.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/FolderLinks/index.js
  src/components/FolderLinks/style.css
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Nav/index.js
  src/components/Nav/style.css
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/SharedPage/index.js
  src/pages/SharedPage/style.css
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/colors.css
  src/styles/global.css
  src/styles/reset.css
  src/utils.js
Labels: 순한맛🐑 

#174 [오영곤] Week6
  public/favicon.ico
  public/images/default_card.svg
  public/images/facebook.svg
  public/images/instargram.svg
  public/images/linkbrary.svg
  public/images/profile.svg
  public/images/search.svg
  public/images/twitter.svg
  public/images/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/cardList/cardList.css
  src/components/cardList/cardList.js
  src/components/contents/contents.css
  src/components/contents/contents.js
  src/components/css/common.css
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/hooks/folderInfo.js
  src/components/hooks/userProfile.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#175 [박진아] Week6
  .prettierrc
  README.md
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/components/Card.jsx
  src/components/Card.scss
  src/components/Favorite.jsx
  src/components/Favorite.scss
  src/components/Footer.jsx
  src/components/Footer.scss
  src/components/Header.jsx
  src/components/Header.scss
  src/components/SearchBar.jsx
  src/components/SearchBar.scss
  src/hooks/useQuery.js
  src/img/ic-facebook.png
  src/img/ic-instagram.png
  src/img/ic-myprofile.svg
  src/img/ic-search.svg
  src/img/ic-smile.svg
  src/img/ic-twitter.png
  src/img/ic-youtube.png
  src/img/img-default.svg
  src/img/logo.svg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 순한맛🐑 

#183 [고현우] Week6
  README.md
  index.html
  package-lock.json
  package.json
  public/index.html
  script/signin.js
  script/signup.js
  script/validation.js
  signin.html
  signup.html
  src/App.css
  src/App.js
  src/App.test.js
  src/api/api.js
  src/assets/Search.png
  src/assets/eye-off.svg
  src/assets/facebook.svg
  src/assets/google.svg
  src/assets/hero.png
  src/assets/image1.png
  src/assets/image2.png
  src/assets/image3.png
  src/assets/image4.png
  src/assets/instagram.svg
  src/assets/kakao.png
  src/assets/library.webp
  src/assets/logo.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/App.js
  src/components/App.module.css
  src/components/Card.js
  src/components/Card.module.css
  src/components/Container.js
  src/components/Container.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/LinkItem.js
  src/components/LinkItem.module.css
  src/components/ListPage.js
  src/components/ListPage.module.css
  src/components/Nav.js
  src/components/Nav.module.css
  src/components/SearchBar.module.css
  src/components/UserMenu.js
  src/components/UserMenu.module.css
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/FolderListPage.js
  src/pages/FolderListPage.module.css
  src/reportWebVitals.js
  src/setupTests.js
  src/signin.css
  src/signup.css
  src/style.css
  src/utils/dateFormatter.js
Labels: 매운맛🔥

#197 [김범주]Week7
  package-lock.json
  package.json
  public/images/Search.png
  public/images/addpurple.png
  public/images/addwhite.png
  public/images/delete.png
  public/images/eye-off.svg
  public/images/eye-on.svg
  public/images/facebook.svg
  public/images/google.png
  public/images/hero.png
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/instagram.svg
  public/images/kakaotalk.png
  public/images/link.svg
  public/images/logo.svg
  public/images/pen.png
  public/images/share.png
  public/images/star.png
  public/images/twitter.svg
  public/images/youtube.svg
  src/Card.css
  src/api.js
  src/components/AddLink/AddLink.css
  src/components/AddLink/AddLink.js
  src/components/App.js
  src/components/Card.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Folder.js
  src/components/Folder/Folder.css
  src/components/Folder/Folder.js
  src/components/FolderFilter/FolderList.css
  src/components/FolderFilter/FolderList.js
  src/components/LinkLogo/LinkLogo.js
  src/components/LinkString/LinkString.css
  src/components/LinkString/LinkString.js
  src/components/Links/Links.css
  src/components/Links/Links.js
  src/components/ListButton/ListButton.css
  src/components/ListButton/ListButton.js
  src/components/Nav.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/Option/Option.css
  src/components/Option/Option.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Sns/Sns.css
  src/components/Sns/Sns.js
  src/index.js
  src/pages/App.js
  src/pages/FolderPage/FolderPage.css
  src/pages/FolderPage/FolderPage.js
  src/utils/timeDifferenceCalculate.js
Labels: 순한맛🐑 

#208 [최무현] Week7
  package-lock.json
  package.json
  src/api.js
  src/assets/back_dog.png
  src/assets/bed.png
  src/assets/building_sky.png
  src/assets/car_image.png
  src/assets/delete.svg
  src/assets/kebab.png
  src/assets/link.svg
  src/assets/myprofile.svg
  src/assets/myprofile_bg.svg
  src/assets/orange_light.png
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/smile_face.svg
  src/assets/some_line.png
  src/assets/table_chair.png
  src/assets/three_light.png
  src/assets/yellow_dog.png
  src/assets/즐겨찾기.png
  src/components/AddLinkBar.css
  src/components/AddLinkBar.js
  src/components/App.css
  src/components/App.js
  src/components/Banner.js
  src/components/Card.css
  src/components/Card.js
  src/components/Cards.js
  src/components/Content.css
  src/components/Content.js
  src/components/Header.css
  src/components/Header.js
  src/components/SearchBar.css
  src/hooks/useGetFolderAsync.js
  src/hooks/useGetFolderListAsync.js
  src/hooks/useGetUserAsync.js
  src/hooks/useGetUserFolderAsync.js
  src/index.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/utils/calculateWhenItIsCreated.js
  src/utils/formatDate.js
Labels: 매운맛🔥, 미완성

#202 [노진석] week7
  package-lock.json
  package.json
  src/App.js
  src/apis/api.js
  src/assets/images/add.svg
  src/assets/images/delete.svg
  src/assets/images/folder-add.svg
  src/assets/images/kebab.svg
  src/assets/images/link.svg
  src/assets/images/pen.svg
  src/assets/images/share.svg
  src/assets/images/star.svg
  src/components/Card.jsx
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/CardList/CardList.css
  src/components/CardList/CardList.jsx
  src/components/CtaButton/CtaButton.jsx
  src/components/CtaButton/CtaButton.module.css
  src/components/FloatingActionButton/FloatingActionButton.jsx
  src/components/FloatingActionButton/FloatingActionButton.module.css
  src/components/FolderListButton/FolderListButton.jsx
  src/components/FolderListButton/FolderListButton.module.css
  src/components/FolderNameLine/FolderNameLine.jsx
  src/components/FolderNameLine/FolderNameLine.module.css
  src/components/Footer/Footer.jsx
  src/components/Kebab/Kebab.jsx
  src/components/Kebab/Kebab.module.css
  src/components/LinkAddForm/LinkAddForm.jsx
  src/components/LinkAddForm/LinkAddForm.module.css
  src/components/LinkSearchForm/LinkSearchForm.jsx
  src/components/LinkSearchForm/SearchForm.module.css
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/NoLinkBlock/NoLinkBlock.jsx
  src/components/NoLinkBlock/NoLinkBlock.module.css
  src/hooks/useEffectOnce.js
  src/hooks/useFetchData.js
  src/pages/FolderPage.jsx
  src/pages/FolderPage.module.css
  src/pages/SharedPage.css
  src/pages/SharedPage.jsx
  src/utils/imageData.js
Labels: 매운맛🔥

#198 [고기호] Week7
  .eslintrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/GlobalStyle.jsx
  src/assets/images/Search.svg
  src/assets/images/add.svg
  src/assets/images/codeit.svg
  src/assets/images/facebook_icon.svg
  src/assets/images/instagram_icon.svg
  src/assets/images/kebab.svg
  src/assets/images/link.svg
  src/assets/images/logo.svg
  src/assets/images/mobile_add.svg
  src/assets/images/no_image_source.svg
  src/assets/images/pen.svg
  src/assets/images/share.svg
  src/assets/images/star.svg
  src/assets/images/trash_can.svg
  src/assets/images/twitter_icon.svg
  src/assets/images/youtube_icon.svg
  src/components/CardList/Card/Card.css
  src/components/CardList/Card/Card.jsx
  src/components/CardList/Card/CardContent/CardContent.jsx
  src/components/CardList/Card/CardImg/CardImg.jsx
  src/components/CardList/CardList.css
  src/components/CardList/CardList.jsx
  src/components/CardList/Search/Search.css
  src/components/CardList/Search/Search.jsx
  src/components/Folder/Folder.css
  src/components/Folder/Folder.jsx
  src/components/FolderCollection/FolderCollection.jsx
  src/components/FolderCollection/FolderTitle/FolderTitle.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/HeaderProfile/HeaderProfile.jsx
  src/components/Hero/Hero.jsx
  src/components/Hero/LinkCreator.jsx/LinkCreator.jsx
  src/components/Hero/ShareDescription/ShareDescription.jsx
  src/index.js
  src/pages/FolderPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/SharedPage.jsx
  src/utils/calculatePassedTime.js
  src/utils/getFetch.js
  src/utils/getFormattedCamelCaseData.js
  src/utils/getFormattedDate.js
Labels: 매운맛🔥

#203 [이시열] Week7
  .eslintrc.json
  .vscode/settings.json
  netlify.toml
  package-lock.json
  package.json
  src/App.jsx
  src/Hooks/useFolderLinks.js
  src/asset/addfolder.svg
  src/asset/addfolderwhite.svg
  src/asset/deleteIcon.svg
  src/asset/kebab.svg
  src/asset/link.svg
  src/asset/penIcon.svg
  src/asset/shareIcon.svg
  src/asset/star.svg
  src/components/AddLink/AddLink.jsx
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/Card/CardList.jsx
  src/components/Card/NoLinkCard.jsx
  src/components/Error/Error.jsx
  src/components/Folder/AddFolder.jsx
  src/components/Folder/Folder.jsx
  src/components/Folder/FolderArea.css
  src/components/Folder/FolderArea.jsx
  src/components/Folder/FolderBody.jsx
  src/components/Folder/FolderCardHeader.jsx
  src/components/Folder/FolderCardList.jsx
  src/components/Folder/FolderContent.jsx
  src/components/Folder/FolderInfo.css
  src/components/Folder/FolderInfo.jsx
  src/components/Folder/FolderTitle.jsx
  src/components/Folder/FolderTitleList.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Home/Home.jsx
  src/components/Home/HomeBody.jsx
  src/components/Layout/Layout.jsx
  src/components/Loading/Loading.jsx
  src/components/Navbar/NavProfile.css
  src/components/Navbar/NavProfile.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarContent.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/Shared/Shared.jsx
  src/components/Shared/SharedBody.jsx
  src/components/Shared/SharedBodyContents.jsx
  src/components/Shared/SharedInfo.jsx
  src/constants/api.js
Labels: 매운맛🔥

#212 [조예진] week7
  public/assets/add-icon-white.svg
  public/assets/add-icon.svg
  public/assets/avatar.svg
  public/assets/bin-icon.svg
  public/assets/icon-facebook-fill.svg
  public/assets/icon-instagram-fill.svg
  public/assets/icon-twitter-fill.svg
  public/assets/icon-youtube-fill.svg
  public/assets/link-icon.svg
  public/assets/logo.svg
  public/assets/no-img.svg
  public/assets/pen-icon.svg
  public/assets/profile-img.svg
  public/assets/search-icon.svg
  public/assets/share-icon.svg
  public/index.html
  src/App.js
  src/apis/api.js
  src/components/AddFolderButton/AddFolderButton.css
  src/components/AddFolderButton/AddFolderButton.js
  src/components/AddLinkForm/AddLinkForm.js
  src/components/Card.js
  src/components/CardList.js
  src/components/CardList/Card/Card.css
  src/components/CardList/Card/Card.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/Content.js
  src/components/Content/Content.css
  src/components/Content/Content.js
  src/components/Folder/FolderButton.js
  src/components/Folder/FolderList.js
  src/components/Folder/constants.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Navbar.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/SearchBar.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/hooks/useFolderData.js
  src/hooks/useLinkDataByFolderId.js
  src/hooks/useUserData.js
  src/index.js
  src/pages/FolderPage.js
  src/pages/SharedLinkPage.js
  src/utils/calDate.js
  src/utils/calElapsedTime.js
Labels: 매운맛🔥

#207 [이재명]Week7
  package-lock.json
  package.json
  public/images/facebook.svg
  public/images/instagram.svg
  public/images/login.png
  public/images/logo.svg
  public/images/twitter.svg
  public/images/wrong-link.png
  public/images/youtube.svg
  public/index.html
  src/.env
  src/App.css
  src/App.js
  src/api.js
  src/api/api.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header.css
  src/components/Header.jsx
  src/components/Header/AddLink.css
  src/components/Header/AddLink.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/NavBar.css
  src/components/Header/NavBar.js
  src/components/Section.jsx
  src/components/Section/Card.css
  src/components/Section/Card.js
  src/components/Section/EditFolder.css
  src/components/Section/EditFolder.js
  src/components/Section/SearchLink.css
  src/components/Section/SearchLink.js
  src/components/Section/Section.css
  src/components/Section/Section.js
  src/components/Section/SortedFolder.css
  src/components/Section/SortedFolder.js
  src/components/color.css
  src/index.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/styles/index.css
  src/utils/dateUtils.js
Labels: 매운맛🔥, 미완성

#215 [백진영] week7
  package-lock.json
  package.json
  public/assets/FAB.png
  public/assets/addBtn.png
  public/assets/delete.png
  public/assets/kebab.png
  public/assets/link.png
  public/assets/pen.png
  public/assets/share.png
  public/assets/star.png
  src/App.css
  src/App.js
  src/CardContainer/CardContainer.css
  src/CardContainer/CardContainer.js
  src/ContentsArea/ContentsArea.js
  src/api/api.js
  src/components/AddLinkArea/AddLinkArea.css
  src/components/AddLinkArea/AddLinkArea.js
  src/components/AddLinkInput/AddLinkInput.css
  src/components/AddLinkInput/AddLinkInput.js
  src/components/CardContainer/CardContainer.css
  src/components/CardContainer/CardContainer.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/ContentsArea/ContentsArea.css
  src/components/ContentsArea/ContentsArea.js
  src/components/Dropdown/Dropdown.css
  src/components/Dropdown/Dropdown.js
  src/components/EditButtonsArea/EditButtonsArea.css
  src/components/EditButtonsArea/EditButtonsArea.js
  src/components/EmptyArea/EmptyArea.css
  src/components/EmptyArea/EmptyArea.js
  src/components/FolderInfo/FolderInfo.css
  src/components/FolderInfo/FolderInfo.js
  src/components/FolderListArea/FolderListArea.css
  src/components/FolderListArea/FolderListArea.js
  src/components/Footer/Footer.css
  src/components/Header/Header.js
  src/components/Kebab/Kebab.css
  src/components/Kebab/Kebab.js
  src/constant/imageUrl.js
  src/context/FolderNameContext.js
  src/pages/Folder/Folder.css
  src/pages/Folder/Folder.js
  src/pages/LinkShared/LinkShared.js
  src/utils/setCardListTitle.js
Labels: 매운맛🔥

#194 [조현진] Week 7
  package-lock.json
  package.json
  public/imgs/03_땡깡-1.gif
  public/imgs/Search.png
  public/imgs/_close.png
  public/imgs/add.png
  public/imgs/delete.png
  public/imgs/kebab.png
  public/imgs/link.png
  public/imgs/pen.png
  public/imgs/share.png
  public/imgs/star.png
  public/imgs/링크복사아이콘.png
  public/imgs/추가하기버튼.png
  public/imgs/카카오톡아이콘.png
  public/imgs/페이스북아이콘.png
  src/App.js
  src/api.js
  src/components/Footer.css
  src/components/common/Footer.js
  src/components/common/Utils.js
  src/components/folder/FolderContentCard.js
  src/components/folder/FolderList.js
  src/components/folder/FolderName.js
  src/components/folder/FolderSearchInput.js
  src/components/folder/FolderSection.js
  src/components/folder/Header.js
  src/components/folder/LinkSearchInput.js
  src/components/folder/Modal.css
  src/components/folder/ModalContent.js
  src/components/folder/ModalManager.js
  src/components/folder/Modals.js
  src/components/folder/Nav.js
  src/components/shared/Header.css
  src/components/shared/Header.js
  src/components/shared/ShareSection.css
  src/components/shared/ShareSection.js
  src/hooks/useModals.js
  src/index.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/styles/reset.css
Labels: 순한맛🐑 

#199 [박준용] Week7
  README.md
  package-lock.json
  package.json
  src/App.js
  src/Main.js
  src/assets/add.svg
  src/assets/delete.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/url.js
  src/components/AddLink/AddLink.css
  src/components/AddLink/AddLink.js
  src/components/App.css
  src/components/App.js
  src/components/Card/Card.css
  src/components/FloatingActionButton/FloatingActionButton.css
  src/components/FloatingActionButton/FloatingActionButton.js
  src/components/Header/Header.js
  src/components/Main/Main.css
  src/components/Search/Search.css
  src/components/Section/Section.css
  src/components/Section/Section.js
  src/components/UserSection/UserSection.css
  src/components/UserSection/UserSection.js
  src/index.js
  src/pages/Folder.css
  src/pages/Folder.js
  src/pages/FolderEmpty.js
  src/pages/HomePage.css
  src/pages/HomePage.js
Labels: 매운맛🔥

#200 [최지희] week6
  package-lock.json
  package.json
  public/favicon.ico
  public/img/catImage.png
  public/img/codeit_logo.svg
  public/img/facebook.svg
  public/img/instagram.svg
  public/img/logo.svg
  public/img/no_image.png
  public/img/search.svg
  public/img/twitter.svg
  public/img/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/getFolder.js
  src/api/getUser.js
  src/card/Card.css
  src/card/Card.js
  src/card/CardContent.css
  src/card/CardContent.js
  src/card/CardImage.css
  src/card/CardImage.js
  src/card/CardList.css
  src/card/CardList.jsx
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Main.css
  src/components/Main.js
  src/components/Profile.css
  src/components/Profile.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/getElapsedTime.jsx
Labels: 매운맛🔥

#233 [조예진] week8
  package-lock.json
  package.json
  public/assets/check-icon.svg
  public/assets/close-icon.svg
  public/assets/icon-kakao-fill.svg
  public/assets/kebab-icon.svg
  public/assets/star-icon.svg
  src/apis/api.js
  src/components/AddFolderButton/AddFolderButton.css
  src/components/AddFolderButton/AddFolderButton.js
  src/components/AddLinkForm/AddLinkForm.js
  src/components/AddLinkForm/AddLinkForm.jsx
  src/components/AddLinkForm/AddLinkForm.module.css
  src/components/CardList/Card/Card.js
  src/components/CardList/Card/Card.jsx
  src/components/CardList/Card/Card.module.css
  src/components/CardList/CardList.js
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.module.css
  src/components/CardList/OptionBox.jsx
  src/components/Content/Content.jsx
  src/components/Content/Content.module.css
  src/components/FloatingButton/FloatingButton.js
  src/components/FloatingButton/FloatingButton.module.css
  src/components/Folder/FolderButton.jsx
  src/components/Folder/FolderList.js
  src/components/Folder/FolderList.jsx
  src/components/Folder/FolderList.module.css
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/SelectFolderBox.jsx
  src/components/Modal/SelectFolderBox.module.css
  src/components/Modal/SelectFolderItem.jsx
  src/components/Modal/SelectFolderItem.module.css
  src/components/Modal/ShareIconBox.jsx
  src/components/Modal/ShareIconBox.module.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.module.css
  src/components/PopOver/PopOver.jsx
  src/components/PopOver/PopOver.module.css
  src/components/SearchBar/SearchBar.js
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.module.css
  src/hooks/useFolderData.js
  src/pages/FolderPage.jsx
  src/pages/SharedLinkPage.jsx
Labels: 매운맛🔥, 미완성

#225 [권지민] week8
  .gitignore
  craco.config.js
  jsconfig.json
  package-lock.json
  package.json
  public/assets/images/icons/checkIconPrimary.svg
  public/assets/images/icons/clipboard.svg
  public/assets/images/icons/closeIcon.svg
  public/assets/images/icons/facebookColored.svg
  public/assets/images/icons/kakao.svg
  public/assets/images/main/main_banner.png
  public/index.html
  public/netlify.toml
  src/App.css
  src/App.js
  src/api/api.js
  src/common.css
  src/components/AddLinkBar/AddLinkBar.js
  src/components/CardList/CardList.js
  src/components/CardListTitle/CardListTitle.js
  src/components/CardTextBox/CardTextBox.js
  src/components/CardThumbnail/CardThumbnail.js
  src/components/CheckBox/CheckBox.js
  src/components/FolderTitleArea/FolderTitleArea.js
  src/components/GradientButton/GradientButton.css
  src/components/GradientButton/GradientButton.js
  src/components/Header/Header.js
  src/components/IconArea/IconArea.js
  src/components/KebabButton/KebabButton.js
  src/components/MobileAddFolderButton/MobileAddFolderButton.js
  src/components/Modal/Modal.js
  src/components/SearchBar/index.js
  src/components/SnsShare/SnsShareGroup.js
  src/components/SortingBar/SortingBar.css
  src/components/SortingBar/SortingBar.js
  src/constants.js
  src/hooks/useModal.js
  src/pages/Folder/Folder.js
  src/pages/Shared/Shared.js
  src/util.js
Labels: 순한맛🐑 

#238 [김범주]Week8
  package-lock.json
  package.json
  public/images/_close.png
  public/images/check.png
  public/images/shareclip.png
  public/images/sharefacebook.png
  public/images/sharekakaotalk.png
  public/index.html
  src/api.js
  src/components/AddLink/AddLink.js
  src/components/Card/Card.js
  src/components/FolderFilter/FolderList.js
  src/components/ListButton/ListButton.js
  src/components/Option/Option.js
  src/components/footer/FooterLinks/FooterLinks.css
  src/components/footer/FooterLinks/FooterLinks.js
  src/components/footer/LinkLogo/LinkLogo.js
  src/components/footer/LinkString/LinkString.css
  src/components/footer/LinkString/LinkString.js
  src/components/footer/Sns/Sns.css
  src/components/footer/Sns/Sns.js
  src/components/header/AddLink/AddLink.css
  src/components/header/AddLink/AddLink.js
  src/components/header/Folder/Folder.css
  src/components/header/Folder/Folder.js
  src/components/header/Nav/Nav.css
  src/components/header/Nav/Nav.js
  src/components/header/Profile/Profile.css
  src/components/header/Profile/Profile.js
  src/components/section/BaseModal/BaseModal.css
  src/components/section/BaseModal/BaseModal.js
  src/components/section/Card/Card.css
  src/components/section/Card/Card.js
  src/components/section/DropDown/DropDown.css
  src/components/section/DropDown/DropDown.js
  src/components/section/EditOption/EditOption.css
  src/components/section/EditOption/EditOption.js
  src/components/section/FolderList/FolderList.css
  src/components/section/FolderList/FolderList.js
  src/components/section/FolderListButton/FolderListButton.css
  src/components/section/FolderListButton/FolderListButton.js
  src/components/section/Search/Search.css
  src/components/section/Search/Search.js
  src/pages/App.js
  src/pages/FolderPage/FolderPage.js
Labels: 미완성, 순한맛🐑 

#241 [김성훈] Week8
  .prettierrc.json
  public/_redirects
  public/_redirects.html
  public/images/Chat.png
  public/images/More.png
  public/images/Telegram.png
  public/images/cancel.png
  public/images/cancel2.png
  public/images/check.png
  public/index.html
  public/netlify.toml
  src/App.js
  src/components/ActionContainer.js
  src/components/Cardlist.js
  src/components/FolderContent.js
  src/components/FolderList.js
  src/components/FolderProfile.js
  src/components/KebabMenu.js
  src/components/LinkCard.js
  src/components/LinkForm.js
  src/components/Modal.js
  src/components/api/KakaoShareButton.js
  src/components/api/fetchFolderProfileData.js
  src/components/api/fetchProfileData.js
  src/components/hooks/useFetchCardsData.js
  src/components/hooks/useFetchFolders.js
  src/components/hooks/useModal.js
  src/components/profile.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/styles/ActionContainer.css
  src/styles/FolderContent.css
  src/styles/KebabMenu.css
  src/styles/LinkCard.css
  src/styles/Modal.css
Labels: 매운맛🔥

#242 [최무현] Week8
  src/assets/facebook_share.svg
  src/assets/kakao_share.svg
  src/assets/modal_close_icon.svg
  src/components/AddLinkBar.js
  src/components/App.css
  src/components/Card.css
  src/components/Card.js
  src/components/Cards.css
  src/components/Content.css
  src/components/Content.js
  src/components/Footer.css
  src/components/Header.css
  src/components/Modal.css
  src/components/Modal.js
  src/hooks/useModal.js
  src/pages/Folder.js
Labels: 미완성

#195 [오영곤] Week7
  package-lock.json
  package.json
  public/images/add.svg
  public/images/delete.svg
  public/images/floating_add.svg
  public/images/kebab.svg
  public/images/link.svg
  public/images/pen.svg
  public/images/share.svg
  public/images/star.svg
  src/App.js
  src/components/contents/cardList/cardList.css
  src/components/contents/cardList/cardList.js
  src/components/contents/contents.css
  src/components/contents/contents.js
  src/components/contents/folderContents/FolderContents.js
  src/components/contents/folderContents/FolderGroup.js
  src/components/contents/folderContents/folderContents.css
  src/components/contents/sharedContents/SharedContents.js
  src/components/footer/footer.js
  src/components/header/folderHeader/FolderHeader.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/sharedHeader/SharedHeader.js
  src/components/hooks/folderInfo.js
  src/components/hooks/userProfile.js
  src/components/navigatorBar/NavigatorBar.js
  src/pages/Folder.js
  src/pages/Home.js
  src/pages/Shared.js
  src/styles/common.css
Labels: 매운맛🔥

#211 [박진아] Week7
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  src/App.jsx
  src/apis.js
  src/components/Card.jsx
  src/components/card/Card.jsx
  src/components/card/card.scss
  src/components/favorite/Favorite.jsx
  src/components/favorite/favorite.scss
  src/components/folder/AddLink.jsx
  src/components/folder/Folder.jsx
  src/components/folder/FolderListButton.jsx
  src/components/folder/addLink.scss
  src/components/folder/folder.scss
  src/components/folder/folderListButton.scss
  src/components/footer/Footer.jsx
  src/components/footer/footer.scss
  src/components/header/Header.jsx
  src/components/header/header.scss
  src/components/searchBar/SearchBar.jsx
  src/components/searchBar/searchBar.scss
  src/hooks/useQuery.js
  src/img/ic-add-w.svg
  src/img/ic-add.svg
  src/img/ic-delete.svg
  src/img/ic-edit.svg
  src/img/ic-kebab.svg
  src/img/ic-link.svg
  src/img/ic-share.svg
  src/img/ic-star.svg
  src/index.js
Labels: 매운맛🔥

#210 [고현우] Week7
  .gitignore
  package-lock.json
  package.json
  src/Main.jsx
  src/api/api.js
  src/components/App.js
  src/components/App.jsx
  src/components/App.module.css
  src/components/LinkItem.js
  src/components/ListPage.js
  src/components/Nav.js
  src/components/button/Button.jsx
  src/components/button/Button.module.css
  src/components/card/Card.jsx
  src/components/card/Card.module.css
  src/components/container/Container.jsx
  src/components/container/Container.module.css
  src/components/folderMenu/FolderMenu.jsx
  src/components/folderMenu/FolderMenu.module.css
  src/components/folderMenu/addFolderButton/AddFolderButton.jsx
  src/components/folderMenu/addFolderButton/AddFolderButton.module.css
  src/components/folderMenu/addFolderButton/FloatingActionButton.jsx
  src/components/folderMenu/addFolderButton/FloatingActionButton.module.css
  src/components/folderMenu/folderEditor/FolderEditor.jsx
  src/components/folderMenu/folderEditor/FolderEditor.module.css
  src/components/folderMenu/folderSelector/FolderSelector.jsx
  src/components/folderMenu/folderSelector/FolderSelector.module.css
  src/components/footer/Footer.jsx
  src/components/footer/Footer.module.css
  src/components/header/Header.jsx
  src/components/header/nav/Nav.jsx
  src/components/header/nav/Nav.module.css
  src/components/linkInput/LinkInput.module.css
  src/components/linkItem/LinkItem.jsx
  src/components/linkItem/LinkItem.module.css
  src/components/listPage/ListPage.jsx
  src/components/listPage/ListPage.module.css
  src/components/searchBar/SearchBar.module.css
  src/components/userMenu/UserMenu.js
  src/components/userMenu/UserMenu.module.css
  src/index.jsx
  src/pages/FolderListPage.js
  src/pages/folderPage/FolderPage.jsx
  src/pages/folderPage/FolderPage.module.css
  src/pages/sharedPage/SharedPage.jsx
  src/pages/sharedPage/SharedPage.module.css
  src/utils/dateFormatter.js
Labels: 매운맛🔥

#234 [심은주] Week6
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/defalutimg.png
  src/assets/facebook.svg
  src/assets/instagram.svg
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/profileicon.svg
  src/assets/search.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Cta/Cta.css
  src/components/Header/Cta/Cta.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/UserProfile/UserProfile.css
  src/components/Header/UserProfile/UserProfile.jsx
  src/components/Main/Card/Card.css
  src/components/Main/Card/Card.jsx
  src/components/Main/Cardlist/Cardlist.css
  src/components/Main/Cardlist/Cardlist.jsx
  src/components/Main/Main.jsx
  src/components/Main/Searchbar/Searchbar.css
  src/components/Main/Searchbar/Searchbar.jsx
  src/components/Main/main.css
  src/components/Titlebar/Titlebar.css
  src/components/Titlebar/Titlebar.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/api.js
  src/utils/calculateDate.js
Labels: 순한맛🐑 

#227 [노진석] week8
  .gitignore
  netlify.toml
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/apis/api.js
  src/assets/imageData.js
  src/assets/images/modal-footer-icon-check.svg
  src/assets/images/modal-icon-facebook.svg
  src/assets/images/modal-icon-kakao.svg
  src/assets/images/modal-link.svg
  src/assets/images/modalClose.svg
  src/components/Card/Card.jsx
  src/components/CardList/CardList.jsx
  src/components/CtaButton/CtaButton.jsx
  src/components/CtaButton/CtaButton.module.css
  src/components/FloatingActionButton/FloatingActionButton.jsx
  src/components/FolderListButton/FolderListButton.jsx
  src/components/FolderListButton/FolderListButton.module.css
  src/components/FolderNameLine/FolderNameLine.jsx
  src/components/FolderNameLine/FolderNameLine.module.css
  src/components/Footer/Footer.jsx
  src/components/Kebab/Kebab.jsx
  src/components/Kebab/Kebab.module.css
  src/components/LinkAddForm/LinkAddForm.jsx
  src/components/LinkSearchForm/LinkSearchForm.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.styled.jsx
  src/components/Modal/ModalAddLink/AddFolderListBox.jsx
  src/components/Modal/ModalAddLink/ModalAddLink.jsx
  src/components/Modal/ModalDelete.jsx
  src/components/Modal/ModalForm.jsx
  src/components/Modal/ModalShare/ModalShare.jsx
  src/components/Modal/ModalShare/ModalShareLinkIcon.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/FolderPage.jsx
  src/pages/SharedPage.jsx
  src/utils/facebookShare.js
  src/utils/kakaoShare.js
  src/utils/util.js
Labels: 매운맛🔥

#218 [고기호] Week8
  .eslintrc
  .gitignore
  netlify.toml
  src/App.jsx
  src/Constants/Constants.js
  src/api/api.js
  src/assets/images/_close.svg
  src/assets/images/check.svg
  src/assets/images/modal_facebook.svg
  src/assets/images/modal_kakao.svg
  src/assets/images/modal_link.svg
  src/components/Contents/CardList/CardDescription/CardDescription.jsx
  src/components/Contents/CardList/CardImg/CardImg.jsx
  src/components/Contents/CardList/CardList.jsx
  src/components/Contents/CardSearchBar/CardSearchBar.jsx
  src/components/Contents/Contents.jsx
  src/components/Contents/FolderCollection/FolderCollection.jsx
  src/components/FolderCollection/FolderCollection.jsx
  src/components/FolderCollection/FolderTitle/FolderTitle.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Header/HeaderProfile/HeaderProfile.jsx
  src/components/Hero/Hero.jsx
  src/components/Hero/LinkCreator.jsx/LinkCreator.jsx
  src/components/Hero/ShareDescription/ShareDescription.jsx
  src/components/Modal/ChangeFolderName.jsx
  src/components/Modal/CreateFolder.jsx
  src/components/Modal/DeleteFolder.jsx
  src/components/Modal/DeleteLink.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalContent/ModalCloseButton.jsx
  src/components/Modal/ModalContent/ModalContentWrapper.jsx
  src/components/Modal/ModalContent/ModalCtaButton.jsx
  src/components/Modal/ModalContent/ModalFolderList.jsx
  src/components/Modal/ModalContent/ModalInput.jsx
  src/components/Modal/ModalContent/ModalInputContainer.jsx
  src/components/Modal/ModalContent/ModalTarget.jsx
  src/components/Modal/ModalContent/ModalTitle.jsx
  src/components/Modal/ModalContent/ModalTitleContainer.jsx
  src/components/Modal/ModalContent/ModalUpdateFolderCollection.jsx
  src/components/Modal/ShareFolder.jsx
  src/components/Modal/UpdateFolder.jsx
  src/globalStyle/GlobalStyle.jsx
  src/hooks/useGetFolderListData.jsx
  src/hooks/useGetKakaoSdkScript.jsx
  src/hooks/useGetShareCardList.jsx
  src/hooks/useGetSharePageData.jsx
  src/hooks/useGetSharePageFolderName.jsx
  src/hooks/useGetsharePageIds.jsx
  src/index.js
  src/pages/FolderPage.jsx
  src/pages/SharedPage.jsx
  src/services/getTargetFolderName.js
  src/utils/copySharingLinkToClipBoard.js
  src/utils/handleModal.js
  src/utils/shareToFacebook.js
  src/utils/shareToKakao.js
Labels: 매운맛🔥

#232 [이시열] Week8
  .eslintrc.json
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/Hooks/useFolderLinks.js
  src/Hooks/useKakaoInit.js
  src/asset/Facebook.svg
  src/asset/Kakao.svg
  src/asset/check.svg
  src/asset/close.svg
  src/asset/logo2.png
  src/components/AddLink/AddLink.jsx
  src/components/Card/Card.jsx
  src/components/Card/CardList.jsx
  src/components/Folder/AddFolder.jsx
  src/components/Folder/Folder.jsx
  src/components/Folder/FolderBody.jsx
  src/components/Folder/FolderCardHeader.jsx
  src/components/Folder/FolderCardList.jsx
  src/components/Folder/FolderContent.jsx
  src/components/Folder/FolderTitle.jsx
  src/components/Folder/FolderTitleList.jsx
  src/components/Modal/AddFolder.jsx
  src/components/Modal/AddLinksToFolder.jsx
  src/components/Modal/ChangeFolderName.jsx
  src/components/Modal/DeleteFolder.jsx
  src/components/Modal/DeleteLink.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/PopOverMenu.jsx
  src/components/Modal/ShareFolder.jsx
  src/components/Navbar/Navbar.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/Shared/SharedInfo.jsx
  src/utils/shareKakao.js
Labels: 매운맛🔥

#228 [백진영] week8
  netlify.toml
  package-lock.json
  package.json
  public/_redirects
  public/assets/check.png
  public/assets/close.png
  public/assets/modal_facebook.png
  public/assets/modal_kakao.png
  public/assets/modal_link.png
  public/index.html
  src/components/AddLinkInput/AddLinkInput.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/ContentsArea/ContentsArea.js
  src/components/Dropdown/Dropdown.js
  src/components/EditButtonsArea/EditButtonsArea.js
  src/components/FolderListArea/FolderListArea.js
  src/components/Footer/Footer.js
  src/components/Kebab/Kebab.js
  src/components/Modal/ModalAddFolder.js
  src/components/Modal/ModalAddLink.js
  src/components/Modal/ModalDeleteFolder.js
  src/components/Modal/ModalDeleteLink.js
  src/components/Modal/ModalEditFolderName.js
  src/components/Modal/ModalShareFolder.js
  src/context/FolderNameContext.js
Labels: 매운맛🔥

#231 [조성경] week8
  .eslintrc.json
  .prettierrc
  assets/css/color.css
  assets/css/index.css
  assets/css/reset.css
  assets/css/sign.css
  assets/images/index/facebook.svg
  assets/images/index/hero.png
  assets/images/index/image1.png
  assets/images/index/image2.png
  assets/images/index/image3.png
  assets/images/index/image4.png
  assets/images/index/instagram.svg
  assets/images/index/landing-image.webp
  assets/images/index/logo.svg
  assets/images/index/twitter.svg
  assets/images/index/youtube.svg
  assets/images/signin/eye-off.svg
  assets/images/signin/eye-on.svg
  assets/images/signin/google.png
  assets/images/signin/kakao.png
  faq.html
  folder.html
  index.html
  package-lock.json
  package.json
  pages/common/config/errorMessage.js
  pages/common/config/helper.js
  pages/common/config/regex.js
  pages/domain/user.js
  pages/login/login.js
  pages/login/loginController.js
  pages/login/loginView.js
  pages/login/signin.html
  pages/signup/signUp.js
  pages/signup/signUpController.js
  pages/signup/signUpView.js
  pages/signup/signup.html
  privacy.html
  src/assets/images/modal/close.svg
  src/components/folder/folderLinkCard.js
  src/components/folder/folderList.js
  src/components/folder/mainHeader.js
  src/components/folder/mainIconButton.js
  src/components/folder/style/mainIconButton.style.js
  src/components/modals/modal.jsx
  src/components/modals/modal/CommonModalStyles.js
  src/components/modals/modal/FolderAdd.jsx
  src/components/modals/modal/FolderDelete.jsx
  src/components/modals/modal/FolderNameChange.jsx
  src/contexts/ModalContext.js
  src/index.js
  src/pages/folder.js
Labels: 미완성, 순한맛🐑 

#240 [조현진] week8
  src/components/folder/FolderContentCard.js
  src/components/folder/FolderName.js
  src/components/folder/Modal.css
  src/components/folder/ModalContent.js
Labels: 미완성, 순한맛🐑 
